name       : gnome-vfs
version    : 2.24.4
release    : 9
source     :
    - https://download.gnome.org/sources/gnome-vfs/2.24/gnome-vfs-2.24.4.tar.bz2 : 62de64b5b804eb04104ff98fcd6a8b7276d510a49fbd9c0feb568f8996444faa
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : desktop.library
summary    : This is the GNOME Virtual File System.
description: |
    GNOME VFS is currently used as one of the foundations of the Nautilus file manager.
builddeps  :
    - pkgconfig(avahi-core)
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-mime-data-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(gtk-doc)
    - pkgconfig(krb5)
    - bzip2-devel
    - libgcrypt-devel
setup      : |
    %patch -Np1 -i $pkgfiles/enable-deprecated.patch
    %patch -Np1 -i $pkgfiles/gnutls-config.patch
    %patch -Np1 -i $pkgfiles/gnutls-3.4.0.patch
    %patch -Np1 -i $pkgfiles/gcrypt-config.patch
    sed -i -s 's|$(srcdir)/auto-test|auto-test|' test/Makefile.am
    libtoolize --force
    gtkdocize
    %reconfigure --disable-static \
        --disable-howl \
        --disable-openssl \
        --enable-avahi \
        --enable-gnutls
build      : |
    %make
install    : |
    %make_install
