name       : gnome-vfs
version    : 2.24.4
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/gnome-vfs/2.24/gnome-vfs-2.24.4.tar.gz : 2eb84be8d260e3c4f13b68e820acf4100e97956f6953067a99119fa8d88c5c00
license    :
    - GPL-2.0
    - LGPL-2.0
summary    : This is the GNOME Virtual File System.
description: |
    GNOME VFS is currently used as one of the foundations of the Nautilus file manager.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-mime-data-2.0)
    - pkgconfig(avahi-core)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
